### ISSUE TITLE
Error: "msys-2.0.dll" failed to initialize

### ISSUE THREAD

**Issue by CrackedP0t** [TeaCI/tea-ci#8] opened 2016-06-22 18:35 UTC
https://github.com/CrackedP0t/LuaNoise
When I try to build with this repository, it fails. Here's the log:

```

[info] Pulling image plugins/drone-git:latest
Drone Git Plugin built from 43dcd64
$ git init
Initialized empty Git repository in /drone/src/github.com/CrackedP0t/LuaNoise/.git/
$ git remote add origin https://github.com/CrackedP0t/LuaNoise.git
$ git fetch --no-tags origin +refs/heads/master:
From https://github.com/CrackedP0t/LuaNoise
* branch            master     -> FETCH_HEAD
* [new branch]      master     -> origin/master
$ git reset --hard -q 38fdd58a24f83dbf7758e8d8ac389c7a2e3726c5
[info] Pulling image teaci/msys32:latest
err:module:attach_process_dlls "msys-2.0.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"C:\\msys32\\usr\\bin\\mintty.exe" failed, status c0000005
     9 [main] mintty 38 fork: child -1 - forked process 41 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
Mintty could not detach from caller, starting anyway.
err:module:attach_process_dlls "msys-2.0.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"C:\\msys32\\usr\\bin\\mintty.exe" failed, status c0000005
 39982 [main] mintty 38 fork: child -1 - forked process 47 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
```

**Comment by ghost** [comment] 2016-06-23 01:06
@CrackedP0t thanks for report, sorry for the delay, it's caused by recent server upgrade, we are working on a fix, will notice you once it's fixed.

You can also consider join https://gitter.im/TeaCI/drone to get noticed for accident report in the future.

Thank you!

**Comment by ghost** [comment] 2016-06-23 14:56
Should be fixed, please retest, thanks!

**Comment by ghost** [comment] 2016-09-03 05:00
No response from original reporter, close as it has fixed for others for long time. Reopen if you have trouble, thanks!

**Closed as completed by ghost** 2016-09-03 05:00 UTC

**Comment by jhasse** [comment] 2016-12-21 13:19
No matter what I do, I'm running into the same problem. See e. g. https://hub.docker.com/r/jhasse/msys2/builds/b3jtfgv3g2commqr2ptr2va/
